### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by danielwys** [Deunitato/CS3103-Project-Group-11#1]
Functionality:
- [x] CLI quiz app (Charlotte)
- [x] Netstat logging (Joshua)
- [x] Camera streaming via HTTP using VLC (Ze Yuan)
- [x] Email netstat log and answers at the end of the quiz (Daniel)
